name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:

env:
  PHP_CS_FIXER_IGNORE_ENV: 1
  XDEBUG_MODE: coverage

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.4
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check types
        run: vendor/bin/phpstan analyse

      - name: Check style
        run: vendor/bin/php-cs-fixer check

      - name: Run test suite
        run: vendor/bin/pest --coverage --coverage-clover=coverage.xml --debug

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
